### ISSUE TITLE
Cannot join to MySQL database - PDO Exception

### ISSUE THREAD

**Issue by ToMmysek795** [mathhulk/advancedban-panel#50] opened 2018-07-30 13:03 UTC
I installed the Panel, set up the language + set up the dB connection = Connection refused

But, i can connect from my PC with MySQL Workbench (Remote client)

Please help.

**Comment by ToMmysek795** [comment] 2018-07-30 13:08
P.S: Remote clients are allowed, because i can join the Database, and edit it without problems.

**Comment by ToMmysek795** [comment] 2018-07-30 14:54
P.S: I have PHP 7.1

**Comment by winnipeg21** [comment] 2018-08-02 16:17
Are you using remote MySQL connection for server to panel? Cause that's needed, it can't be local host unless you site and server are ran on the SAME server. Normally it's different servers.

**Comment by ToMmysek795** [comment] 2018-08-02 21:00
Ehm....

Hosted on Awardspace

Connect to MySQL on GSP Europe (Gamehosting.cz)

**Comment by ToMmysek795** [comment] 2018-08-02 21:00
It connected to MySQL, but the page not worked.

**Comment by ToMmysek795** [comment] 2018-08-02 22:31
Page is working, but i need to insert that crap into page.
![Screenshot](https://user-images.githubusercontent.com/21044779/43614632-7c74fc5a-96b4-11e8-9b1c-430efe908bc2.png)

**Comment by ToMmysek795** [comment] 2018-08-02 22:31
But in code is nothing like MySQL query...

`<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport">
		
		<meta name="msapplication-TileColor" content="#ffffff">
		<meta name="msapplication-TileImage" content="assets/img/icons/ms-icon-144x144.png">
		<meta name="theme-color" content="#ffffff">
		
		<meta name="description" content="Oficialní banlist pro VindeLand">
		<meta property="og:site_name" content="VindeLand - Banlist">
		<meta property="og:title" content="Tresty">
		<meta property="og:image" content="http://vindeland.tk/wp-content/uploads/2018/08/icon.png">
		<meta property="og:description" content="Oficialní banlist pro VindeLand">
		<meta property="og:url" content="//<?= $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] ?>">
		<meta property="og:type" content="website">
		
		<title>VindeLand - Banlist</title>
		
		<link rel="shortcut icon" href="http://vindeland.tk/wp-content/uploads/2018/08/icon.png" type="image/png">
		<link rel="icon" type="image/png" href="http://vindeland.tk/wp-content/uploads/2018/08/icon.png">
		
		<link rel="stylesheet" href="assets/css/bootstrap.min.css" media="screen">
		<link rel="stylesheet" href="assets/css/advancedban-panel.css" media="screen">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" media="screen">
	    <link rel="stylesheet" href="http://banlist.vindeland.tk/include/themes/vindeland/css/style.css" media="screen">
	</head>
	<body>
		<nav class="navbar navbar-default navbar-fixed-top">
		  <div class="container">
			<div class="navbar-header">
				<button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#navbar">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				
				<a class="navbar-brand" href="./">VindeLand - Banlist</a>
			</div>
			<div class="collapse navbar-collapse" id="navbar">
				<ul class="nav navbar-nav">
					<li class="active"><a href="./"><i class="fa fa-gavel" aria-hidden="true"></i> Tresty</a></li>
						<li class="clipboard" data-clipboard-text="mc.vindeland.tk">
							<a>Hráči na serveru: <span class="badge players">N/A</span></a>
						</li>
				</ul>
				
				<ul class="nav navbar-nav navbar-right">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-envelope-open-o" aria-hidden="true"></i> Podpora <span class="caret"></span></a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="http://vindeland.tk/support">Tickety</a></li>
								<li><a href="http://feedback.vindeland.tk">Feedback</a></li>
							</ul>
						</li>
				</ul>
			</div>
		  </div>
		</nav>
		
		<div class="container">
			<div class="jumbotron">
				<h1>VindeLand - Banlist</h1> 
				<p>Oficialní banlist pro server Vindeland.</p>
			</div>
			
			<div class="jumbotron">
				<div class="search">
					<input type="text" class="form-control" id="input" placeholder="Hledat hráče...">
					<div class="dropdown">
						<button class="btn btn-default dropdown-toggle" type="button" id="type" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Typ <span class="caret"></span></button>
						<ul class="dropdown-menu" aria-labelledby="type">
							<li><a data-search="ban">Ban</a></li>
							<li><a data-search="temp_ban">Doč. Ban</a></li>
							<li><a data-search="mute">Umlčení</a></li>
							<li><a data-search="temp_mute">Doč. umlčení</a></li>
							<li><a data-search="warning">Varování</a></li>
							<li><a data-search="temp_warning">Doč. varování</a></li>
							<li><a data-search="kick">Kick</a></li>
							<?php
							
							if($__public["ip_ban"] === true) {
								
								?>
								<li><a data-search="ip_ban">IP Ban</a></li>
								<?php
								
							}
							
							?>
						</ul>
					</div>
					<div class="dropdown">
						<button class="btn btn-default dropdown-toggle" type="button" id="status" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Status <span class="caret"></span></button>
						<ul class="dropdown-menu" aria-labelledby="status">
							<li><a data-search="active">Aktivní</a></li>
							<li><a data-search="inactive">Neaktivní</a></li>
						</ul>
					</div>
					<div class="dropdown">
						<button class="btn btn-default dropdown-toggle" type="button" id="search" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Hledat <span class="caret"></span></button>
						<ul class="dropdown-menu" aria-labelledby="search">
							<li><a data-search="name">Nick</a></li>
							<li><a data-search="reason">Důvod</a></li>
							<li><a data-search="operator">Admin</a></li>
						</ul>
					</div>
				</div>
			</div>
			
			<div class="jumbotron">
				<div class="text-center">
					<ul class="pagination">
						
					</ul>
				</div>
				<div class="table-wrapper">
					<table class="table table-striped table-hover">
						<thead>
							<tr>
								<th>Nick</th>
								<th>Důvod</th>
								<th>Admin</th>
								<th>Datum</th>
								<th>Expirace</th>
								<th>Typ</th>
								<th class="text-right">Status</th>
							</tr>
						</thead>
						<tbody>
							
						</tbody>
					</table>
				</div>
				<div class="text-center">
					<ul class="pagination">
						
					</ul>
				</div>
			</div>
		</div>
		
		<script type="text/javascript" src="assets/js/jquery-3.2.1.min.js"></script>
		<script type="text/javascript" src="assets/js/bootstrap.min.js"></script>
		<script type="text/javascript" src="assets/js/clipboard.min.js"></script>
		<script type="text/javascript" src="assets/js/advancedban-panel.js"></script>
	</body>
</html>`

**Comment by winnipeg21** [comment] 2018-08-02 22:39
Use the latest ver of AB-web or the update before the current update. By looking at Awardspace web hosting it appears they don't offer remote mysql. May I ask where your server is hosted from and you website. If you are running both on the same VPS it should work. If you are running on different sites or different servers this also won't work. https://www.heliohost.org <-- that has remote mysql as it appears. If you are using a minecraft server host (ex: mcph) it will most likely come with remote mysql.

**Comment by ToMmysek795** [comment] 2018-08-02 23:31
"Hello Sevenisko,

Thank you for contacting us.

Your outgoing connections are enabled so you should be able to connect to external servers. Please make sure that the external server is allowing connections to their databases from the outside.

Feel free to reopen this ticket in case you have more questions or you need further assistance. Thank you for choosing our services.

Best Regards,
Anthony Thomson
Dedicated Support Team
Supportindeed.com"

They support remote connections

MC server hosted on Gamehosting.cz (Crew.sk/GSP Slovakia) - They supports remove connections

**Comment by ToMmysek795** [comment] 2018-08-02 23:32
P.S: I can connect to MC MySQL server from my PC (MySQL Workbench) = Remote connection

**Comment by mathhulk** [comment] 2018-08-02 23:40
Punishments and sorting are dealt with through the client and not the server. I looked into your issue and the problem is that http://banlist.vindeland.tk/punishments/ seems to be redirecting to http://vindeland.tk/500.html. This path is used to request the punishments from the server and, because the request cannot go through, the punishments are not listed on the page. I would suggest looking for an error report or log in the folder that AdvancedBan Panel was loaded into.

**Comment by mathhulk** [comment] 2018-08-02 23:40
Apologies, I did not mean to close this issue.

**Comment by ToMmysek795** [comment] 2018-08-03 17:17
Can i PM you FTP connection to banlist?

**Comment by winnipeg21** [comment] 2018-08-03 17:31
I recommend reinstalling ab-web. By looking at your banlist it looks messed up.

**Comment by ToMmysek795** [comment] 2018-08-03 17:59
Reinstalled 3x = Not working

**Comment by ToMmysek795** [comment] 2018-08-03 18:00
1. JSON Files are not loading, because they cannot be opened...

somepath/file.json = somepath/.json - :/

That's not a fault of Webhosting, i had an PHP file with JSON files, and they worked.

**Comment by ToMmysek795** [comment] 2018-08-03 18:03
For mathhulk - Can i solve that with you via mail?

Adress: seven9@vindeland.tk

**Comment by winnipeg21** [comment] 2018-08-03 18:07
Join his discord for faster response. Email is just to slow

**Closed** 2018-08-06 04:43 UTC
Labels: bug, fixed
